# Exercise 3 - Tree Reduce

**GOAL:** The goal of this exercise is to show how to implement a tree reduce in Ray by passing object IDs into remote functions to encode dependencies between tasks.

In this exercise, you will use Ray to implement parallel data generation and a parallel tree reduction.

In [1]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import numpy as np
import ray
import time

In [2]:
ray.init(num_cpus=8, redirect_output=True)

Waiting for redis server at 127.0.0.1:56045 to respond...
Waiting for redis server at 127.0.0.1:51393 to respond...
Starting local scheduler with 8 CPUs, 0 GPUs

View the web UI at http://localhost:8889/notebooks/ray_ui78220.ipynb?token=e68bc145609e9d72b3a56cffc3a52a6b6fd87e77c637f9af



{'local_scheduler_socket_names': ['/tmp/scheduler95345149'],
 'node_ip_address': '127.0.0.1',
 'object_store_addresses': [ObjectStoreAddress(name='/tmp/plasma_store90280572', manager_name='/tmp/plasma_manager93033245', manager_port=29974)],
 'redis_address': '127.0.0.1:56045',
 'webui_url': 'http://localhost:8889/notebooks/ray_ui78220.ipynb?token=e68bc145609e9d72b3a56cffc3a52a6b6fd87e77c637f9af'}

**EXERCISE:** These functions will need to be turned into remote functions so that the tree of tasks can be executed in parallel.

In [3]:
# This is a proxy for a function which generates some data.
@ray.remote
def create_data(i):
    time.sleep(0.3)
    return i * np.ones(10000)

# This is a proxy for an expensive aggregation step (which is also
# commutative and associative so it can be used in a tree-reduce).
@ray.remote
def aggregate_data(x, y):
    time.sleep(0.3)
    return x * y

**EXERCISE:** Make the data creation tasks run in parallel. Also aggregate the vectors in parallel. Note that the `aggregate_data` function must be called 7 times. They cannot all run in parallel because some depend on the outputs of others. However, it is possible to first run 4 in parallel, then 2 in parallel, and then 1.

In [29]:
def process(vectors, count):
    start = 0
    results = []
    while start <= count:
        result = aggregate_data.remote(vectors[start], vectors[start+1])
        start += 1
        results.append(result)
    return results, vectors[count:]

In [30]:
result, v = process(vectors, 4)

In [31]:
result, v

([ObjectID(bcc1fb5ec2690cf1cb4b15e68d2a3a39823a64de),
  ObjectID(37fbc3a6bdd29f825843e729735ae7f63bcd9b23),
  ObjectID(f927f349bd369ed9cab2aa21056bbbcbe9e82dbd),
  ObjectID(ef3246260eaa7e11a2d03c088e2a836912effdea),
  ObjectID(98e6702a2061aa67e2aab1c0204c526d98083091)],
 [array([5., 5., 5., ..., 5., 5., 5.]),
  array([6., 6., 6., ..., 6., 6., 6.]),
  array([7., 7., 7., ..., 7., 7., 7.]),
  array([8., 8., 8., ..., 8., 8., 8.])])

In [32]:
res2, v2 = process(v, 2)

In [33]:
res2

[ObjectID(47e243d9466dc2365e63aa165fd200e07445d1a4),
 ObjectID(0f670eb0578cca7cee674e049c52a0c0a9b87d63),
 ObjectID(4324cc7f79a3c5653a7f46373d81ffea671fe132)]

In [34]:
v2

[array([7., 7., 7., ..., 7., 7., 7.]), array([8., 8., 8., ..., 8., 8., 8.])]

In [15]:
# Sleep a little to improve the accuracy of the timing measurements below.
time.sleep(2.0)
start_time = time.time()

# EXERCISE: Here we generate some data. Do this part in parallel.
vectors = [create_data.remote(i + 1) for i in range(8)]
vectors = [ray.get(v) for v in vectors]

# Here we aggregate all of the data repeatedly calling aggregate_data. This
# can be sped up using Ray.
#
# NOTE: A direct translation of the code below to use Ray will not result in
# a speedup because each function call uses the output of the previous function
# call so the function calls must be executed serially.
#
# EXERCISE: Speed up the aggregation below by using Ray. Note that this will
# require restructuring the code to expose more parallelism. First run 4 tasks
# aggregating the 8 values in pairs. Then run 2 tasks aggregating the resulting
# 4 intermediate values in pairs. then run 1 task aggregating the two resulting
# values. Lastly, you will need to call ray.get to retrieve the final result.
# result = aggregate_data.remote(vectors[0], vectors[1])
# result = aggregate_data.remote(result, vectors[2])
# result = aggregate_data.remote(result, vectors[3])
# result = aggregate_data.remote(result, vectors[4])
# result = aggregate_data.remote(result, vectors[5])
# result = aggregate_data.remote(result, vectors[6])
# result = ray.get(aggregate_data.remote(result, vectors[7]))


        
    

# NOTE: For clarity, the aggregation above is written out as 7 separate function
# calls, but this can be done more easily in a while loop via
#
# while len(vectors) > 1:
#     vectors = aggregate_data(vectors[0], vectors[1]) + vectors[2:]
# result = vectors[0]
#
# When expressed this way, the change from serial aggregation to tree-structured
# aggregation can be made simply by appending the result of aggregate_data to the
# end of the vectors list as opposed to the beginning.
#
# EXERCISE: Think about why this is true.

end_time = time.time()
duration = end_time - start_time

TypeError: unsupported operand type(s) for +: 'common.ObjectID' and 'list'

In [12]:
result, duration

(array([40320., 40320., 40320., ..., 40320., 40320., 40320.]),
 2.4459292888641357)

**EXERCISE:** Use the UI to view the task timeline and to verify that the vectors were aggregated with a tree of tasks.

You should be able to see the 8 `create_data` tasks running in parallel followed by 4 `aggregate_data` tasks running in parallel followed by 2 more `aggregate_data` tasks followed by 1 more `aggregate_data` task.

In the timeline, click on **View Options** and select **Flow Events** to visualize tasks dependencies.

In [20]:
import ray.experimental.ui as ui
ui.task_timeline()

**VERIFY:** Run some checks to verify that the changes you made to the code were correct. Some of the checks should fail when you initially run the cells. After completing the exercises, the checks should pass.

In [19]:
assert np.all(result == 40320 * np.ones(10000)), ('Did you remember to '
                                                  'call ray.get?')
assert duration < 0.3 + 0.9 + 0.3, ('FAILURE: The data generation and '
                                    'aggregation took {} seconds. This is '
                                    'too slow'.format(duration))
assert duration > 0.3 + 0.9, ('FAILURE: The data generation and '
                              'aggregation took {} seconds. This is '
                              'too fast'.format(duration))

print('Success! The example took {} seconds.'.format(duration))

AssertionError: FAILURE: The data generation and aggregation took 2.4502809047698975 seconds. This is too slow